compileUtil:
	./gradlew :util:build

compileServer:
	./gradlew :server:build

runServer:
	java -jar server/build/libs/server-1.0.jar -p 51342

compileClient:
	./gradlew :client:build

runClient:
	java -jar client/build/libs/client-1.0.jar -i localhost -p 51342 -f /Users/improvedmac/Documents/improved/coding/java/network/fileTransfer/client/src/main/resources/amd.psd
